import { createRequestHandler, type ServerBuild } from "react-router";
// This path only exists after `npm run build`. Wrangler bundles
// workers/app.ts at deploy time after the build has run, so the file
// is there at bundle time — but not at typecheck time, hence the ignore.
// @ts-ignore - generated by `npm run build`
import * as buildImport from "../dist/server/index.js";
const build = buildImport as unknown as ServerBuild;

declare module "react-router" {
  export interface AppLoadContext {
    cloudflare: {
      env: Env;
      ctx: ExecutionContext;
    };
  }
}

const handler = createRequestHandler(build, "production");

export default {
  async fetch(request, env, ctx) {
    return handler(request, {
      cloudflare: { env, ctx },
    });
  },
} satisfies ExportedHandler<Env>;
